### ISSUE TITLE
Test points on TX ann RX lines between ICs should use larger test point package

### ISSUE THREAD

**Issue by ghost** [sparkfun/CAN-Bus_Shield#11]
The vias used for current test points are too small and the stop mask circles drawn on bottom layer are too small. Larger "3X5" test point package should work.

**Comment by ToniCorinne** [comment]
Replaced. Question though - the QC check list says through-hole is preferable, so does the TP through-hole package need to be updated?

**Comment by ghost** [comment]
The "through hole preferable" I believe refers to through hole header pads not a specific test point package in eagle. We should probably rethink the verbage in the checklist...
