### ISSUE TITLE
9-pin connector pinout

### ISSUE THREAD

**Issue by cjevans76** [sparkfun/CAN-Bus_Shield#14]
Thanks for the work on this board - certainly worth a beer!  I'm just trying to get it to work and noticed that the pinout on the 9-way connector appears to be non-standard.  Every CAN bus I've ever worked with has this configuration:
pin 2: CAN-Low (CAN-)
pin 3: GND (Ground) - NOT ALWAYS USED
pin 7: CAN-High (CAN+)
pin 9: CAN V+ (Power) - NOT ALWAYS USED
I don't think there is anything in the ISO standard, but it's on the Wiki page for CAN so it must be true :)
It's not a huge issue - I can re-wire my 9-pin connector, but it does make the board harder to use with other CAN products (e.g. the ones from Kvaser, Softing, Vektor, ATI etc) which all use pins 2 & 7.  If the board ever does get re-spun it might be something to put on the to-do list.

**Comment by ToniCorinne** [comment]
@cjevans76 we are actually working on a revision where this will be a configurable option. There are a lot of products that use both pinouts, so we want to make it available for as many users as possible. 

Thanks for the feedback!
