### ISSUE TITLE
Dashed grey lines needed to separate parts of sch

### ISSUE THREAD

**Issue by ghost** [sparkfun/CAN-Bus_Shield#3]

**Comment by ToniCorinne** [comment]
The schematic is separated by functionality sections  already(LCD, Arduino, uSD, CAN-Bus). I don't think it'd be great to split the CAN-Bus section down further, but if you can suggest a way that would make sense, I'm all ears.

**Comment by ghost** [comment]
Good enough.

**Comment by ToniCorinne** [comment]
Ok, closing this out then.
